### ISSUE TITLE
Can't resize image to 250x250

### ISSUE THREAD

**Issue by electricshaman** [elixir-vision/picam#29]
The port crashes when you try to set the image size to 250x250.

**Comment by GregMefford** [comment]
This is working now as of `0.4.0` because I fixed a few "rounding error" type things as part of #41, specifically by [using the `VCOS_ALIGN_UP` function](https://github.com/elixir-vision/picam/pull/41/files#diff-79b58e89980e1b2013c1155773805d21R55) to make sure the sizes are aligned to valid numbers.
