### ISSUE TITLE
Add support for Raspberry Pi can V2

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-vision/picam#39]
I leaving this here as reported from ElixirConfEU that the new version of the cam doesn’t function properly. https://www.raspberrypi.org/products/camera-module-v2/

I haven’t verified this, needs research

**Comment by fhunleth** [comment]
There must be more to this, since I’d bet that most people using picam have v2 cameras. I’ve used them in training classes and I assume that’s what Greg uses.

**Comment by elliotthilaire** [comment]
I just bought a Picam v2 that I intended to use with this library. I’ll test it out soon and report back.

**Comment by thomis** [comment]
Thanks @mobileoverlord and @fhunleth for taking this up. I bumped into a timeout issue while calling Picam.next_frame() when setting a higher resolution (e.g. Picam.set_size(1920, 0)). Found this previous closed issue [#23](https://github.com/elixir-vision/picam/issues/23). I was trying to increase  #define MAX_DATA_BUFFER_SIZE to 1572864 (6 times previous value of 262144) in raspijpgs.c. With new settings re-compile, re-burn I was able to take frames with a resolution of 3280*2464. No idea what optimal value here is. Should mention that my camera is labeled with Raspberry Pi Camera V2.1 and using it on a Raspberry Pi 3 Model B+.

**Comment by GregMefford** [comment]
Hey, sorry for the delayed response on this!
Picam definitely supports the V2 camera (it's the main one that I use).

Regarding the internal buffer size - yes, it's really frustrating to me as well that the buffer is finite and limits the quality of output images. I'd like to track that issue separately in #37 since that seems to be the main issue there.

I think I'll close this issue unless someone here can demonstrate a hardware configuration where the V2 camera doesn't work, other than the issue with high-resolution images that log errors about hitting the `MAX_DATA_BUFFER_SIZE`.
